#: .\mcserver\templates\admin\set_subject.html:6
msgid "home"
msgstr "Home"

#: .\mcserver\templates\admin\set_subject.html:9
msgid "set_subject"
msgstr "Set Subject"

#: .\mcserver\templates\admin\set_subject.html:14
msgid "set_subject_confirmation"
msgstr "Are you sure you want to set the subject for the next list of sessions?"

#: .\mcserver\templates\email\reset_password_email.html:11
msgid "reset_password_email_greeting"
msgstr "Hi,"

#: .\mcserver\templates\email\reset_password_email.html:12
msgid "reset_password_email_your_username"
msgstr "Your username is:"

#: .\mcserver\templates\email\reset_password_email.html:15
msgid "reset_password_email_click_button"
msgstr "To reset your password click on the following button:"

#: .\mcserver\templates\email\reset_password_email.html:18
msgid "reset_password_email_reset_button_text"
msgstr "Reset my Password"

#: .\mcserver\templates\email\reset_password_email.html:21
msgid "reset_password_email_token"
msgstr "If the button if not working, click on the following token:"

#: .\mcserver\templates\email\reset_password_email.html:23
msgid "reset_password_email_ignore"
msgstr "If you did not request to retrieve your username or change your password, you can ignore this email."

#: .\mcserver\templates\email\reset_password_email.html:26
msgid "reset_password_email_team"
msgstr "OpenCap Team."

#: .\mcserver\templates\email\verification_email.html:11
msgid "verification_code_email_greeting"
msgstr "Hi,"

#: .\mcserver\templates\email\verification_email.html:12
msgid "verification_code_email_your_code"
msgstr "Your verification code is:"

#: .\mcserver\templates\email\verification_email.html:20
msgid "verification_code_email_copy_paste"
msgstr "Please copy-paste it to the OpenCap webapp."

#: .\mcserver\templates\email\verification_email.html:23
msgid "verification_code_email_ignore"
msgstr "If you did not try to log in into OpenCap, you can ignore this email."

#: .\mcserver\templates\email\verification_email.html:26
msgid "verification_code_email_team"
msgstr "OpenCap Team."

#: .\mcserver\views.py:171 .\mcserver\views.py:207 .\mcserver\views.py:246
#: .\mcserver\views.py:323 .\mcserver\views.py:355 .\mcserver\views.py:382
#: .\mcserver\views.py:452 .\mcserver\views.py:495 .\mcserver\views.py:691
#: .\mcserver\views.py:775 .\mcserver\views.py:805 .\mcserver\views.py:864
#: .\mcserver\views.py:943 .\mcserver\views.py:991 .\mcserver\views.py:1061
#: .\mcserver\views.py:1093 .\mcserver\views.py:1158 .\mcserver\views.py:1330
#: .\mcserver\views.py:1364 .\mcserver\views.py:1388 .\mcserver\views.py:1416
#: .\mcserver\views.py:1504 .\mcserver\views.py:1532 .\mcserver\views.py:1559
#: .\mcserver\views.py:1592 .\mcserver\views.py:1616
msgid "undefined_uuid"
msgstr "Undefined UUID."

#: .\mcserver\views.py:184 .\mcserver\views.py:188 .\mcserver\views.py:192
#: .\mcserver\views.py:218 .\mcserver\views.py:222 .\mcserver\views.py:226
#: .\mcserver\views.py:230 .\mcserver\views.py:234 .\mcserver\views.py:254
#: .\mcserver\views.py:258 .\mcserver\views.py:262 .\mcserver\views.py:266
#: .\mcserver\views.py:270 .\mcserver\views.py:310 .\mcserver\views.py:314
#: .\mcserver\views.py:330 .\mcserver\views.py:334 .\mcserver\views.py:338
#: .\mcserver\views.py:342 .\mcserver\views.py:346 .\mcserver\views.py:365
#: .\mcserver\views.py:369 .\mcserver\views.py:373 .\mcserver\views.py:392
#: .\mcserver\views.py:396 .\mcserver\views.py:400 .\mcserver\views.py:442
#: .\mcserver\views.py:483 .\mcserver\views.py:508 .\mcserver\views.py:537
#: .\mcserver\views.py:541 .\mcserver\views.py:545 .\mcserver\views.py:549
#: .\mcserver\views.py:720 .\mcserver\views.py:724 .\mcserver\views.py:728
#: .\mcserver\views.py:746 .\mcserver\views.py:766 .\mcserver\views.py:788
#: .\mcserver\views.py:792 .\mcserver\views.py:796 .\mcserver\views.py:838
#: .\mcserver\views.py:842 .\mcserver\views.py:846 .\mcserver\views.py:850
#: .\mcserver\views.py:854 .\mcserver\views.py:926 .\mcserver\views.py:930
#: .\mcserver\views.py:948 .\mcserver\views.py:952 .\mcserver\views.py:956
#: .\mcserver\views.py:964 .\mcserver\views.py:968 .\mcserver\views.py:977
#: .\mcserver\views.py:1040 .\mcserver\views.py:1044 .\mcserver\views.py:1076
#: .\mcserver\views.py:1080 .\mcserver\views.py:1133 .\mcserver\views.py:1137
#: .\mcserver\views.py:1141 .\mcserver\views.py:1145 .\mcserver\views.py:1149
#: .\mcserver\views.py:1199 .\mcserver\views.py:1203 .\mcserver\views.py:1207
#: .\mcserver\views.py:1211 .\mcserver\views.py:1215 .\mcserver\views.py:1303
#: .\mcserver\views.py:1344 .\mcserver\views.py:1348 .\mcserver\views.py:1352
#: .\mcserver\views.py:1371 .\mcserver\views.py:1375 .\mcserver\views.py:1379
#: .\mcserver\views.py:1399 .\mcserver\views.py:1403 .\mcserver\views.py:1407
#: .\mcserver\views.py:1427 .\mcserver\views.py:1431 .\mcserver\views.py:1435
#: .\mcserver\views.py:1515 .\mcserver\views.py:1519 .\mcserver\views.py:1523
#: .\mcserver\views.py:1542 .\mcserver\views.py:1546 .\mcserver\views.py:1550
#: .\mcserver\views.py:1571 .\mcserver\views.py:1575 .\mcserver\views.py:1579
#: .\mcserver\views.py:1599 .\mcserver\views.py:1603 .\mcserver\views.py:1607
#: .\mcserver\views.py:1623 .\mcserver\views.py:1627 .\mcserver\views.py:1631
#: .\mcserver\views.py:1639 .\mcserver\views.py:1677 .\mcserver\views.py:1707
#: .\mcserver\views.py:1739 .\mcserver\views.py:1743 .\mcserver\views.py:1794
#: .\mcserver\views.py:1798 .\mcserver\views.py:1833 .\mcserver\views.py:1847
#: .\mcserver\views.py:1851 .\mcserver\views.py:1874 .\mcserver\views.py:1879
msgid "error"
msgstr "Error: %(error_message)"

#: .\mcserver\views.py:185 .\mcserver\views.py:219 .\mcserver\views.py:255
#: .\mcserver\views.py:331 .\mcserver\views.py:366 .\mcserver\views.py:393
#: .\mcserver\views.py:509 .\mcserver\views.py:542 .\mcserver\views.py:721
#: .\mcserver\views.py:789 .\mcserver\views.py:839 .\mcserver\views.py:927
#: .\mcserver\views.py:949 .\mcserver\views.py:1041 .\mcserver\views.py:1077
#: .\mcserver\views.py:1134 .\mcserver\views.py:1200
msgid "session_uuid_not_found"
msgstr "Sorry, we couldn't find a session with UUID: %(uuid)"

#: .\mcserver\views.py:189 .\mcserver\views.py:231 .\mcserver\views.py:267
#: .\mcserver\views.py:343 .\mcserver\views.py:370 .\mcserver\views.py:397
#: .\mcserver\views.py:546 .\mcserver\views.py:725 .\mcserver\views.py:793
#: .\mcserver\views.py:851 .\mcserver\views.py:931 .\mcserver\views.py:953
#: .\mcserver\views.py:1045 .\mcserver\views.py:1081 .\mcserver\views.py:1146
#: .\mcserver\views.py:1212
msgid "session_uuid_not_valid"
msgstr "Sorry, the session UUID: %(uuid) is not valid"

#: .\mcserver\views.py:193
msgid "calibration_error"
msgstr "There was an error during the calibration step. Please try again."

#: .\mcserver\views.py:223 .\mcserver\views.py:259 .\mcserver\views.py:335
#: .\mcserver\views.py:843 .\mcserver\views.py:1138 .\mcserver\views.py:1204
msgid "login_needed"
msgstr "Sorry, you have to log in to access to this session."

#: .\mcserver\views.py:227 .\mcserver\views.py:263 .\mcserver\views.py:339
#: .\mcserver\views.py:847 .\mcserver\views.py:1142 .\mcserver\views.py:1208
msgid "permission_denied"
msgstr "You do not have permissions to access this data."

#: .\mcserver\views.py:235 .\mcserver\views.py:271
msgid "session_retrieve_error"
msgstr "There was an error while retrieving the session. Please try again."

#: .\mcserver\views.py:311 .\mcserver\views.py:965 .\mcserver\views.py:1516
#: .\mcserver\views.py:1543 .\mcserver\views.py:1572 .\mcserver\views.py:1600
#: .\mcserver\views.py:1624
msgid "subject_uuid_not_found"
msgstr "Sorry, we couldn't find a subject with UUID: %(uuid)"

#: .\mcserver\views.py:315
msgid "session_not_valid"
msgstr "There was an error while checking the validity of the session. Please try again."

#: .\mcserver\views.py:347
msgid "session_permanent_remove_error"
msgstr "There was an error while permanently removing the session. Please try again."

#: .\mcserver\views.py:374
msgid "session_remove_error"
msgstr "There was an error while removing the session. Please try again."

#: .\mcserver\views.py:401
msgid "session_restore_error"
msgstr "There was an error while restoring the session. Please try again."

#: .\mcserver\views.py:443 .\mcserver\views.py:550
msgid "session_create_error"
msgstr "There was an error while creating the session. Please try again."

#: .\mcserver\views.py:484
msgid "qr_retrieve_error"
msgstr "There was an error while retrieving the qr code. Please try again."

#: .\mcserver\views.py:538
msgid "user_not_found"
msgstr "Sorry, we couldn't find the user."

#: .\mcserver\views.py:729
msgid "trial_record_error"
msgstr "There was an error while recording the trial. Please try again."

#: .\mcserver\views.py:747 .\mcserver\views.py:767
msgid "session_download_error"
msgstr "There was an error while downloading the session. Please try again."

#: .\mcserver\views.py:797 .\mcserver\views.py:855
msgid "session_get_settings_error"
msgstr "There was an error while getting the settings of the session. Please try again."

#: .\mcserver\views.py:935
msgid "session_set_metadata_error"
msgstr "There was an error while setting the metadata of the session. Please try again."

#: .\mcserver\views.py:957 .\mcserver\views.py:969 .\mcserver\views.py:978
msgid "subject_assign_error"
msgstr "There was an error while assigning this subject to the session. Please try again."

#: .\mcserver\views.py:1049 .\mcserver\views.py:1085
msgid "trial_cancel_error"
msgstr "There was an error while canceling the trial. Please try again."

#: .\mcserver\views.py:1150
msgid "calibration_image_retrieve_error"
msgstr "There was an error while retrieving the calibration image. Please try again."

#: .\mcserver\views.py:1216
msgid "neutral_image_retrieve_error"
msgstr "There was an error while retrieving the neutral image. Please try again."

#: .\mcserver\views.py:1304
msgid "trial_dequeue_error"
msgstr "There was an error while dequeuing the trials. Please try again."

#: .\mcserver\views.py:1345 .\mcserver\views.py:1372 .\mcserver\views.py:1400
#: .\mcserver\views.py:1428
msgid "trial_uuid_not_found"
msgstr "Sorry, we couldn't find a trial with UUID: %(uuid)."

#: .\mcserver\views.py:1349 .\mcserver\views.py:1376 .\mcserver\views.py:1404
#: .\mcserver\views.py:1432
msgid "trial_uuid_not_valid"
msgstr "Sorry, the trial UUID: %(uuid) is not valid."

#: .\mcserver\views.py:1353
msgid "trial_rename_error"
msgstr "There was an error while renaming the trial. Please try again."

#: .\mcserver\views.py:1380
msgid "trial_permanent_remove_error"
msgstr "There was an error while permanently removing the trial. Please try again."

#: .\mcserver\views.py:1408
msgid "trial_remove_error"
msgstr "There was an error while removing the trial. Please try again."

#: .\mcserver\views.py:1436
msgid "trial_restore_error"
msgstr "There was an error while removing the trial. Please try again."

#: .\mcserver\views.py:1520 .\mcserver\views.py:1547 .\mcserver\views.py:1576
#: .\mcserver\views.py:1604 .\mcserver\views.py:1628
msgid "subject_uuid_not_valid"
msgstr "Sorry, the subject UUID: %(uuid) is not valid"

#: .\mcserver\views.py:1524
msgid "subject_remove_error"
msgstr "There was an error while removing the subject. Please try again."

#: .\mcserver\views.py:1551
msgid "subject_restore_error"
msgstr "There was an error while removing the subject. Please try again."

#: .\mcserver\views.py:1580 .\mcserver\views.py:1608 .\mcserver\views.py:1640
msgid "subject_create_error"
msgstr "There was an error while creating a new subject. Please try again."

#: .\mcserver\views.py:1632
msgid "subject_permanent_remove_error"
msgstr "There was an error while permanently removing the subject. Please try again."

#: .\mcserver\views.py:1678
msgid "user_create_error"
msgstr "There was an error while creating your user. Please try again."

#: .\mcserver\views.py:1692 .\mcserver\views.py:1708
msgid "user_delete_error"
msgstr "There was an error while deleting your user. Please try again."

#: .\mcserver\views.py:1700
msgid "user_removed"
msgstr "The user was removed."

#: .\mcserver\views.py:1702
msgid "user_not_authenticated"
msgstr "Sorry, the user is not authenticated."

#: .\mcserver\views.py:1704
msgid "confirmation_username_not_correct"
msgstr "Looks like the verification code is incorrect. Please double check and try again."

#: .\mcserver\views.py:1740
msgid "credentials_incorrect"
msgstr "Looks like the username or password you entered is incorrect. Please double check and try again."

#: .\mcserver\views.py:1744
msgid "login_error"
msgstr "There was an error while logging in. Please try again."

#: .\mcserver\views.py:1780
msgid "reset_password_email_subject"
msgstr "Opencap - Forgot Username or Password"

#: .\mcserver\views.py:1795
msgid "account_email_not_found"
msgstr "Sorry, we couldn't find an account associated with that email."

#: .\mcserver\views.py:1799
msgid "error_reset_password"
msgstr "There was an error while resetting your password. Please try again."

#: .\mcserver\views.py:1834 .\mcserver\views.py:1848
msgid "reset_password_link_expired"
msgstr "The link to reset your password has expired or does not exist. Try resetting your password again."

#: .\mcserver\views.py:1852
msgid "new_password_creation_error"
msgstr "There was an error while creating your new password. Please try again."

#: .\mcserver\views.py:1875
msgid "verification_error"
msgstr "There was an error during the verification process. Please try again."

#: .\mcserver\views.py:1880
msgid "verification_code_incorrect"
msgstr "Looks like the verification code is incorrect. Please double check and try again."
